---

- name: Import NodeSource GPG Key into APT
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add NodeSource Repo
  apt_repository: repo='deb https://deb.nodesource.com/node_4.x vivid main' state=present

- name: Install System Packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - redis-server
    - nodejs

- name: Symlink NodeJS
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Symlink Vagrant
  file: src=/vagrant dest=/srv/nekobot state=link

- name: Install Global NPM Modules
  npm: name={{ item }} global=yes state=latest
  with_items:
    - npm
    - node-gyp
    - forever

- name: Install NekoBot via npm
  npm: path=/srv/nekobot

- name: Add NekoBot to Services
  template: src=nekobot.tpl dest=/lib/systemd/system/nekobot.service

- name: Enable and Start NekoBot Service
  service: name=nekobot enabled=yes state=started
