---

- name: Import NodeSource GPG Key into APT
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add NodeSource Repo
  apt_repository: repo='deb https://deb.nodesource.com/node_4.x trusty main' state=present

- name: Install System Packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - redis-server
    - nodejs

- name: Symlink NodeJS
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Symlink Vagrant
  file: src=/vagrant dest=/srv/nekobot state=link

- name: Install Global NPM Modules
  npm: name={{ item }} global=yes state=latest
  with_items:
    - node-gyp
    - forever

- name: Install NekoBot via npm
  npm: path=/srv/nekobot

- name: Run NekoBot via Forever
  command: forever start -l /srv/nekobot/logs/nekobot-forever.log -e /srv/nekobot/logs/nekobot-error.log /srv/nekobot/neko.js

- name: Add NekoBot to Startup
  cron: name="nekobot" special_time=reboot job="forever start -l /srv/nekobot/logs/nekobot-forever.log -e /srv/nekobot/logs/nekobot-error.log /srv/nekobot/neko.js"
